name: Git Version

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          version-format: "v{major}.{minor}.{patch}"  # Define your version format

      - name: Use the version
        run: |
          echo "Current version: ${{ steps.version.outputs.version }}"
          echo "Previous version: ${{ steps.version.outputs.previous-version }}"
          
      - name: Increment Patch Version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}